[aws]
disabled = true

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 12

[git_state]
disabled = false #git_state
cherry_pick = "ğŸ’PICK"
revert = "<!--"
merge = ">-"
rebase = "~~>"
am = "ğŸ“¬"
am_or_rebase = "ğŸ“¬~>"

[git_status]
disabled = false #git_status
conflicted = "âš”ï¸ "
staged="âœ”ï¸" 
renamed = "ğŸ†"
deleted = "ğŸ—‘"
modified = "ğŸ“"
ahead = "â¬†ï¸ "
behind = "â¬‡ï¸"
diverged = "ğŸ”€"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
format = '([$all_status$ahead_behind]($style) )'

[nix_shell]
impure_msg = "ğŸ’©"
symbol = "âŠ¢"

[python]
format = '[${symbol}${pyenv_prefix}${version}]($style) '
