[aws]
disabled = true

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 12

[git_state]
disabled = false #git_state
progress_divider = " of "
cherry_pick = "ğŸ’PICK"
revert = "<!--"
merge = ">-"
rebase = "~~>"
am = "ğŸ“¬"
am_or_rebase = "ğŸ“¬~>"

[git_status]
disabled = false #git_status
prefix = ""
suffix = " "
conflicted = "âš”ï¸ "
staged="âœ”ï¸" 
renamed = "ğŸ†"
deleted = "ğŸ—‘"
modified = "ğŸ“"
ahead = "â¬†ï¸ "
behind = "â¬‡ï¸"
diverged = "ğŸ”€"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"

[nix_shell]
impure_msg = "ğŸ’©"
symbol = "âŠ¢"
